Prevent CVE-2023-2878
kyverno/policies pull request #1008
Opened 2024-05-14 22:43 UTC by kurktchiev

## Description
Prevent CVE-2023-2878

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-07-29 20:11 UTC, kurktchiev commented
Note that the test for the CSI secret store are superfluous, unless you actually install a proper CSI driver, the test is kinda meaningless

2024-07-29 20:18 UTC, chipzoller requested changes

2024-07-29 20:18 UTC, chipzoller commented on other/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878.yaml
> +            args: "-v=0 | -v=1"
This is not correct for the matching kinds.

2024-07-29 20:18 UTC, chipzoller commented on other/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878.yaml
> +  annotations:
Missing annotations. See other examples.

2024-07-29 20:18 UTC, chipzoller commented on other/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878.yaml
> +    policies.kyverno.io/subject: Pod, Secret, CSI-Driver
```suggestion
    policies.kyverno.io/subject: Pod, Secret
```

2024-07-29 20:18 UTC, chipzoller commented on other/check-if-using-csi-secrets-store-driver-cve-2023-2878/check-if-using-csi-secrets-store-driver-cve-2023-2878.yaml
> +        kinds:
Must have `any` or `all` under match/exclude.

2024-07-29 20:18 UTC, chipzoller commented on other/check-if-using-csi-secrets-store-driver-cve-2023-2878/check-if-using-csi-secrets-store-driver-cve-2023-2878.yaml
> +  annotations:
Missing annotations.

2024-07-29 20:18 UTC, chipzoller commented on other/check-if-using-csi-secrets-store-driver-cve-2023-2878/check-if-using-csi-secrets-store-driver-cve-2023-2878.yaml
> +    policies.kyverno.io/subject: Pod, Secret, CSI-Driver
```suggestion
    policies.kyverno.io/subject: Pod, Secret
```

2024-07-29 20:18 UTC, chipzoller commented on other/check-if-using-csi-secrets-store-driver-cve-2023-2878/check-if-using-csi-secrets-store-driver-cve-2023-2878.yaml
> +      message: "Potentially vulnerable to CVE-2023-2878."
Message needs improvement. This isn't enough to return to a user.

2024-07-29 20:18 UTC, chipzoller commented on other/check-if-using-csi-secrets-store-driver-cve-2023-2878/check-if-using-csi-secrets-store-driver-cve-2023-2878.yaml
> +        - csidriver
Pretty sure this kind isn't correct. They are case sensitive.

2024-07-29 20:22 UTC, kurktchiev commented on other/check-if-using-csi-secrets-store-driver-cve-2023-2878/check-if-using-csi-secrets-store-driver-cve-2023-2878.yaml
> +        - csidriver
`k get csidrivers.storage.k8s.io` i am missing the `s` though

2024-07-29 20:26 UTC, kurktchiev commented on other/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878.yaml
> +            args: "-v=0 | -v=1"
I do not understand, please can you provide a bit more context?

2024-07-29 20:38 UTC, chipzoller commented on other/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878.yaml
> +            args: "-v=0 | -v=1"
You're matching on Deployments but the pattern isn't accurate for a Deployment, only for a Pod.

2024-07-29 20:39 UTC, chipzoller commented on other/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878.yaml
> +  annotations:
Annotations are [here](https://github.com/kyverno/policies/wiki/Kyverno-annotations). Look at some other samples for what we typically include. minversion isn't necessary unless it uses fields/features from versions within the past 3 releases.

2024-07-29 20:39 UTC, chipzoller commented on other/check-if-using-csi-secrets-store-driver-cve-2023-2878/check-if-using-csi-secrets-store-driver-cve-2023-2878.yaml
> +        - csidriver
A `kubectl get` operates differently from matching kinds. Singular vs. plural also matters. Have you actually tested this yourself with this resource?

2024-07-29 20:41 UTC, kurktchiev commented on other/check-if-using-csi-secrets-store-driver-cve-2023-2878/check-if-using-csi-secrets-store-driver-cve-2023-2878.yaml
> +        - csidriver
i have tested in the playground, where it does pass?

2024-07-29 20:43 UTC, chipzoller commented on other/check-if-using-csi-secrets-store-driver-cve-2023-2878/check-if-using-csi-secrets-store-driver-cve-2023-2878.yaml
> +        - csidriver
You need to test this in a real cluster. Playground doesn't behave the same way when it comes to kind matching.

2024-07-29 20:59 UTC, kurktchiev commented on other/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878.yaml
> +  annotations:
I do not feel like that answered my question, so I guess let me know if the added annotation is what you are looking for

2024-07-29 21:01 UTC, chipzoller commented on other/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878/restrict-secrets-store-csi-driver-loglevel-cve-2023-2878.yaml
> +  annotations:
Ok, sorry. The two which are the most common are `kyverno.io/kyverno-version` (the version of Kyverno on which this policy was tested and confirmed to work) and `kyverno.io/kubernetes-version` (same but for Kubernetes itself). Others look ok.

2024-07-30 13:33 UTC, chipzoller requested changes
Don't see any test cases for these two policies, just some test resources.

2025-08-17 16:28 UTC, JimBugwadia commented
closing stale draft

2025-08-17 16:28 UTC, closed without merging