Cleanup rs with timebound
kyverno/policies pull request #1027
Opened 2024-05-22 07:31 UTC by anuddeeph1

## Description
ReplicaSets serve as an intermediate controller for various Pod controllers like Deployments. When a new version of a Deployment is initiated, it generates a new ReplicaSet with the specified number of replicas and scales down the current one to zero. Consequently, numerous empty ReplicaSets may accumulate in the cluster, leading to clutter and potential false positives in policy reports if enabled. This cleanup policy is designed to remove empty ReplicaSets across the cluster within a specified timeframe, for instance, ReplicaSets created one day ago, ensuring the ability to rollback to previous ReplicaSets in case of deployment issues.

## Checklist
- [] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-05-28 23:52 UTC, chipzoller requested changes

2024-05-28 23:52 UTC, chipzoller commented on cleanup/cleanup-empty-replicasets/rbac.yaml
> +  namespace: kyverno
This isn't necessary. As long as the appropriate labels are present, the permissions will be aggregated.

2024-05-28 23:52 UTC, chipzoller commented on cleanup/cleanup-empty-replicasets/cleanup-empty-replicasets.yaml
> +apiVersion: kyverno.io/v2alpha1
Why are you changing this?

2024-05-28 23:52 UTC, chipzoller commented on cleanup/cleanup-empty-replicasets/cleanup-empty-replicasets.yaml
> +    policies.kyverno.io/title: Cleanup Empty ReplicaSets
Remove trailing space.

2024-05-28 23:52 UTC, chipzoller commented on cleanup/cleanup-empty-replicasets/cleanup-empty-replicasets.yaml
> +      operator: "GreaterThan"
```suggestion
      operator: GreaterThan
```

2024-05-28 23:52 UTC, chipzoller commented on cleanup/cleanup-empty-replicasets/cleanup-empty-replicasets.yaml
> +#The described logic currently deletes the ReplicaSets created 30 seconds ago. You can adjust this timeframe according to your specific requirements.
Please place comments above the intended line, not below.

2024-05-28 23:52 UTC, chipzoller commented on cleanup/cleanup-empty-replicasets/artifacthub-pkg.yml
> +name: cleanup-empty-replicasets-with-timebound
Policy name has not changed. No need to change this.

2024-05-28 23:52 UTC, chipzoller commented on cleanup/cleanup-empty-replicasets/artifacthub-pkg.yml
> +displayName: Cleanup empty replicasets with timebound
Policy name has not changed. No need to change this.

2024-05-29 07:58 UTC, anuddeeph1 reviewed
Updated the changes

2024-05-29 13:50 UTC, chipzoller commented
When you make and complete requested changes, please resolve conversations as you go along so reviewers know you have addressed the comments.

2024-05-31 13:59 UTC, chipzoller requested changes
The `/cleanup` folder has not yet been activated for Chainsaw tests. Would you please also add the appropriate line [here](https://github.com/kyverno/policies/blob/main/.github/workflows/test.yml#L36-L37)?

2024-06-09 12:31 UTC, chipzoller approved these changes

2024-06-09 12:31 UTC, merged