Added policy to deny resources in specified window.
kyverno/policies pull request #1032
Opened 2024-05-24 12:47 UTC by anuddeeph1

## Description
This policy denies the creation and updating of resources specifically for Deployment and Pod kinds during a specified time window. The policy is designed to enhance control over resource modifications during critical periods, ensuring stability and consistency within the Kubernetes environment.

## Checklist
- [] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-05-29 00:04 UTC, chipzoller requested changes
Neat concept. I think it can be useful. I note that your policy does not use the current modern schema. Can you please update this to conform to all the latest specifications?

2024-05-29 09:00 UTC, anuddeeph1 commented
@chipzoller , updated with new schema

2024-05-29 13:49 UTC, chipzoller requested changes
When making policy changes, you will need to modify corresponding/supporting files as well.

2024-05-29 13:49 UTC, chipzoller commented on other/deny-creation-of-resources/deny-creation-of-resources.yaml
> +            - Pod
Suggest only matching on Deployment and not Pod. Will need to update relevant areas of this policy and tests if so.

2024-05-29 13:49 UTC, chipzoller commented on other/deny-creation-of-resources/deny-creation-of-resources.yaml
> +          }}'
Should not be on two lines. Please also add a comment what this does.

2024-05-29 13:49 UTC, chipzoller commented on other/deny-creation-of-resources/deny-creation-of-resources.yaml
> +            operator: In
`In` is deprecated and no longer available. Please use `AnyIn`.

2024-05-29 13:49 UTC, chipzoller commented on other/deny-creation-of-resources/deny-creation-of-resources.yaml
> +      message: Creating and updating resources is not allowed at this time, please contact admin!
```suggestion
      message: Creating and updating resources is not allowed at this time.
```

2024-05-29 13:49 UTC, chipzoller commented on other/deny-creation-of-resources/deny-creation-of-resources.yaml
> +  name: deny-creation-of-resources
Suggest a different name. This isn't just about denying creation but also updates as well.

2024-05-29 13:49 UTC, chipzoller commented on other/deny-creation-of-resources/deny-creation-of-resources.yaml
> +    policies.kyverno.io/title: Deny Creation of Resources
Name

2024-05-29 13:49 UTC, chipzoller commented on other/deny-creation-of-resources/deny-creation-of-resources.yaml
> +  - name: deny-creation-of-resources
Rules should be named differently from policies.

2024-05-31 14:01 UTC, chipzoller requested changes
Please replace instances of the word "updation", which only exists in Indian English, to "updating".

2024-05-31 23:34 UTC, chipzoller approved these changes
Thanks for seeing this process through, @anuddeeph1. You've done good work and we encourage you to make a couple other contributions to become a [recognized contributor](https://kyverno.io/community/#project-roles).

2024-05-31 23:40 UTC, chipzoller requested changes
Sorry, but Chainsaw tests are failing. Need to investigate and solve.

2024-06-03 11:59 UTC, anuddeeph1 commented
> Sorry, but Chainsaw tests are failing. Need to investigate and solve.

Resolved the issues in chainsaw test

2024-06-09 13:56 UTC, chipzoller approved these changes

2024-06-09 13:56 UTC, merged