[Chainsaw Tests] Add Chainsaw test for Bare Pods
kyverno/policies pull request #1057
Opened 2024-06-29 17:19 UTC by Jay179-sudo

## Related Issue(s)
Partial fix for #950 

## Description
Added chainsaw test for bare pods. Also added a test pod and a cluster-role manifest file.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-06-29 17:25 UTC, Jay179-sudo commented
Maybe we can also reduce the scheduled time on the ClusterCleanupPolicy file from five minutes down to one minute to reduce CI time?
Please do let me know if any other issues persist.

2024-07-02 07:17 UTC, realshuting commented
> Maybe we can also reduce the scheduled time on the ClusterCleanupPolicy file from five minutes down to one minute to reduce CI time? Please do let me know if any other issues persist.

Makes sense, can you replicate the same policy and reduce the scheduled time to a minute?

2024-07-02 09:51 UTC, realshuting commented on cleanup/cleanup-bare-pods/cleanup-bare-pods.yaml
> +  schedule: "*/1 * * * *"
Not sure if it's ok to update the original policy, I was thinking to replicate the policy in the test folder and update the schedule.

@chipzoller - is this policy used anywhere else?

2024-07-02 10:57 UTC, realshuting approved these changes

2024-07-02 11:30 UTC, chipzoller requested changes
Please move the ClusterRole inside the `.chainsaw-test` directory.

2024-07-02 11:31 UTC, chipzoller requested changes

2024-07-02 11:31 UTC, chipzoller commented on cleanup/cleanup-bare-pods/.chainsaw-test/cleanup-bare-pods-test.yaml
The policy should not be duplicated like this even if the need is to just modify a field. Please use an appropriate step in the Chainsaw test to modify the `schedule` field of the existing policy.

2024-07-02 11:32 UTC, chipzoller commented on cleanup/cleanup-bare-pods/clusterrole.yaml
> +  - "pods"
```suggestion
  - pods
```

2024-07-02 11:33 UTC, chipzoller commented on cleanup/cleanup-bare-pods/clusterrole.yaml
> +  name: kyverno:cleanup-controller:temp
```suggestion
  name: kyverno:cleanup-controller:barepods
```

2024-07-04 10:05 UTC, Jay179-sudo commented
@chipzoller any updates on this?

2024-07-05 03:41 UTC, mohamedawnallah approved these changes
Great work @Jay179-sudo! 💪 Left some nit comments...

2024-07-05 03:41 UTC, mohamedawnallah commented on cleanup/cleanup-bare-pods/.chainsaw-test/clusterrole.yaml
Rename this file to `cluster-role.yaml` to be consistent with other files in the codebase?

2024-07-05 05:49 UTC, Jay179-sudo commented on cleanup/cleanup-bare-pods/.chainsaw-test/chainsaw-step-02-assert-1.yaml
> +  name: clean-bare-pods
The status.ready field is not defined for a ClusterCleanupPolicy object. It is defined within status.conditions.

When I ran the tests as normal, the status field that does get filled up is the lastExecutionTime field. However, this is an field that only gets filled up after a round of execution which will not allow for direct condition checks in our chainsaw test file.

Wouldn't it be better to skip this field altogether?

![Status Fields during execution](https://github.com/kyverno/policies/assets/70968485/b54f2d26-7f21-4b51-aecb-12e215a1bbc3)

2024-07-05 17:26 UTC, mohamedawnallah commented on cleanup/cleanup-bare-pods/.chainsaw-test/chainsaw-step-02-assert-1.yaml
> +  name: clean-bare-pods
Yes you are right 👍

2024-07-05 17:32 UTC, mohamedawnallah approved these changes

2024-07-06 00:25 UTC, mohamedawnallah commented on cleanup/cleanup-bare-pods/.chainsaw-test/chainsaw-test.yaml
> +            file: clusterrole.yaml
@Jay179-sudo It seems you forgot to rename this as well to `cluster-role.yaml`.

PS:
Also the DCO signing

2024-07-14 14:00 UTC, chipzoller approved these changes

2024-07-14 14:00 UTC, merged