Adding policy for CPU Limits for all container types
kyverno/policies pull request #1067
Opened 2024-07-09 04:54 UTC by nsagark

## Related Issue(s)

## Description

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-07-14 14:18 UTC, chipzoller requested changes

2024-07-14 14:18 UTC, chipzoller commented on other/require-cpu-limits/require-cpu-limits.yaml
> +      resources:
All policies should be using `any`/`all` under the match and exclude conditions.

2024-07-14 14:18 UTC, chipzoller commented on other/require-cpu-limits/require-cpu-limits.yaml
> +      Setting CPU limits on pods ensures fair distribution of resources, preventing any single pod from monopolizing CPU and impacting the performance of other pods. This practice enhances stability,
CPU limits aren't set on Pods, they're set on containers.

2024-07-14 14:18 UTC, chipzoller commented on other/require-cpu-limits/.chainsaw-test/pod-bad.yaml
This test resource manifest needs to cover cases where there are multiple containers (both `containers[]` and `initContainers[]`) in which one container sets a limit while the other does not. You also do not need to include any securityContext fields as these are irrelevant to this policy.

2024-07-14 14:18 UTC, chipzoller commented on other/require-cpu-limits/.kyverno-test/resource.yaml
See similar comment on Chainsaw resource file.

2024-07-18 03:17 UTC, nsagark commented
@chipzoller I have updated the files as per your comments. Please review

2024-07-23 12:22 UTC, chipzoller commented
Are all comments resolved?

2024-07-26 14:00 UTC, nsagark commented
Hi @chipzoller Yes, I have updated the files. Just to make sure to address below comment,

`This test resource manifest needs to cover cases where there are multiple containers (both containers[] and initContainers[]) in which one container sets a limit while the other does not`

I have added below in resource.yaml file. Is that what you meant or something else?

`apiVersion: v1
kind: Pod
metadata:
  name: badpod07
spec:
  initContainers:
  - name: initcontainer01
    image: dummyimagename
  - name: initcontainer02
    image: dummyimagename
  containers:
  - name: container01
    image: dummyimagename
    resources:
      limits:
        cpu: "500m"
  - name: container02
    image: dummyimagename    `

2024-07-29 14:37 UTC, chipzoller commented
Yes

2024-07-29 15:15 UTC, nsagark commented
With that, I have addressed all the comments. Please review.

2024-07-29 15:24 UTC, chipzoller requested changes
Please ensure to resolve all conversations when complete.

2024-07-29 15:24 UTC, chipzoller commented on other/require-cpu-limits/.chainsaw-test/pod-bad.yaml
> +    image: busybox:1.35
Please update this initcontainer with a CPU limit.

2024-07-29 15:24 UTC, chipzoller commented on other/require-cpu-limits/.chainsaw-test/pod-bad.yaml
> +    image: busybox:1.35
This is redundant from badpod01. Remove.

2024-07-29 15:24 UTC, chipzoller commented on other/require-cpu-limits/.chainsaw-test/pod-bad.yaml
> +    image: busybox:1.35
This is redundant from badpod03. Remove.

2024-07-29 15:24 UTC, chipzoller commented on other/require-cpu-limits/.chainsaw-test/podcontroller-bad.yaml
Please make similar changes to this file as those pointed out in `pod-bad.yaml`.

2024-07-29 20:01 UTC, nsagark commented
@chipzoller All conversations are resolved.

2024-07-31 00:20 UTC, chipzoller commented
Several conversations unresolved.

2024-07-31 11:54 UTC, nsagark commented
@chipzoller Sorry, I have resolved previous conversations. Please check now

2024-07-31 12:44 UTC, chipzoller requested changes
Looks good other than the AH digest needing to be updated.

2024-07-31 13:51 UTC, nsagark commented
Hi @chipzoller The AH digest seems to be correct. Am I doing anything wrong below?

Sagar@DESKTOP-VS85098 MINGW64 /c/users/sagar/Downloads/kyverno-prs/policies/other/require-cpu-limits (require-cpu-limits)
$ sha256sum require-cpu-limits.yaml
2fe9fa043fbb4c85da0204a00a60ce6732ac0dc0e3a5ece4f7b741982a1003d1 *require-cpu-limits.yaml

Sagar@DESKTOP-VS85098 MINGW64 /c/users/sagar/Downloads/kyverno-prs/policies/other/require-cpu-limits (require-cpu-limits)
$ ls -lrht
total 8.0K
-rw-r--r-- 1 Sagar 197121 1.5K Jul 31 09:47 require-cpu-limits.yaml
-rw-r--r-- 1 Sagar 197121 1.5K Jul 31 09:47 artifacthub-pkg.yml

2024-07-31 13:56 UTC, chipzoller commented
You're not doing anything wrong, it's just the expected digest is calculated in the pipeline under Linux. You're doing it under Windows which means the digest may be slightly different. The one being reported in the pipeline is `1d9998010342080ae64f309befdf52065de557cdcc10ddf68d8476b5af93d505`. Go ahead and put that in the AH metadata file and it should pass.

2024-07-31 14:13 UTC, nsagark commented
Hi @chipzoller I have updated the digest. Thanks for pointing it out.

2024-08-01 15:58 UTC, nsagark commented
Hi @chipzoller I don't see the changes yet in the main branch. Are we good here or anything missing?

2024-08-01 16:11 UTC, chipzoller approved these changes

2024-08-01 19:53 UTC, merged