Adding files for restrict-clusterrole-mutating-validating-admission-webhooks policy
kyverno/policies pull request #1068
Opened 2024-07-09 05:21 UTC by nsagark

…ebhooks policy

## Related Issue(s)

## Description

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-07-14 14:21 UTC, chipzoller requested changes

2024-07-14 14:21 UTC, chipzoller commented on other/restrict-clusterrole-mutating-validating-admission-webhooks/restrict-clusterrole-mutating-validating-admission-webhooks.yaml
> +              value: true
This is unnecessarily verbose. You can add the `contains()` check into the first `foreach` loop by putting both it and the check for the specific verbs under an `any` block. The first two expressions can remain under the `all`.

2024-07-18 03:40 UTC, nsagark commented
Hi @chipzoller I have updated the policy. Please review

2024-07-29 14:34 UTC, chipzoller commented
Please resolve all comments when re-requesting review. If changes were pushed to address comments, hit the 'Resolve' button so reviewers know.

2024-07-29 14:37 UTC, chipzoller requested changes

2024-07-29 14:37 UTC, chipzoller commented on other/restrict-clusterrole-mutating-validating-admission-webhooks/restrict-clusterrole-mutating-validating-admission-webhooks.yaml
> +      ClusterRoles that grant write permissions over admission webhook should be minimized to reduce powerful identities in the cluster. This policy checks to ensure write permissions are not provide
Missing annotations `kyverno.io/kyverno-version` and `kyverno.io/kubernetes-version`. For more details on annotations, see [here](https://github.com/kyverno/policies/wiki/Kyverno-annotations).

2024-07-31 13:11 UTC, chipzoller requested changes
This looks good other than updating the digest.

2024-07-31 13:55 UTC, nsagark commented
Hi @chipzoller Digest seems to be right. Please take a look.

`$ sha256sum restrict-clusterrole-mutating-validating-admission-webhooks.yaml
f9a1178081876a732a9a43975cdfda007989a8e1d9926281474076f9df48780b *restrict-clusterrole-mutating-validating-admission-webhooks.yaml

Sagar@DESKTOP-VS85098 MINGW64 /c/users/sagar/Downloads/kyverno-prs/policies/other/restrict-clusterrole-mutating-validating-admission-webhooks (restrict-clusterrole-mutating-validating-admission-webhooks)
$ ls -lrht
total 8.0K
-rw-r--r-- 1 Sagar 197121 1.8K Jul 31 09:54 restrict-clusterrole-mutating-validating-admission-webhooks.yaml
-rw-r--r-- 1 Sagar 197121 1.2K Jul 31 09:54 artifacthub-pkg.yml`

2024-07-31 13:56 UTC, chipzoller commented
See comment [here](https://github.com/kyverno/policies/pull/1067#issuecomment-2260589118).

2024-07-31 14:27 UTC, nsagark commented
Hi @chipzoller I have updated the digest.

2024-08-01 23:37 UTC, nsagark commented
Hi @chipzoller Please let me know if anything else is needed here.

2024-08-02 14:09 UTC, merged