Enhance Resource Constraints Validation Policy to Include InitContainers & EphermalContainers
kyverno/policies pull request #1103
Opened 2024-07-31 17:05 UTC by nikhilmaheshwari24

Signed-off-by: nikhilmaheshwari24 [nikhil.m2498@gmail.com](mailto:nikhil.m2498@gmail.com)

## Related Issue(s)
https://github.com/kyverno/policies/issues/951

## Description
This PR updates the existing Kyverno policy to validate CPU and memory resource requests and limits for both containers and initContainers within Pods. This enhancement ensures comprehensive resource management across all container types in a Kubernetes cluster.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-07-31 18:29 UTC, chipzoller requested changes
Thanks for this. Couple things:
1. You must sign off on all commits (DCO).
2. See contribution guide [here](https://github.com/kyverno/policies?tab=readme-ov-file#contribution), specifically the part about updating Artifact Hub metadata file.

2024-07-31 18:29 UTC, chipzoller commented on best-practices/require-pod-requests-limits/require-pod-requests-limits.yaml
> +  - name: validate-container-resources
If you change this, CLI tests will probably break.

2024-08-01 07:22 UTC, realshuting commented
Please sign-off your commits - https://github.com/kyverno/policies/pull/1103/checks?check_run_id=28177145454.

2024-08-02 08:34 UTC, nikhilmaheshwari24 commented
@realshuting @chipzoller Could you please approve this?

2024-08-02 11:49 UTC, chipzoller commented
Unresolved conversations.

2024-08-02 11:52 UTC, chipzoller commented
You have not followed the contribution guide, specifically the part about updating `artifacthub-pkg.yml` file.

2024-08-02 13:06 UTC, chipzoller approved these changes

2024-08-02 13:08 UTC, nikhilmaheshwari24 commented
@chipzoller I apologize. Have signed off the commits & updated the sha256sum to the `artifacthub-pkg.yml` file. 

I'll make sure such mistakes won't be repeated in future contributions.

2024-08-02 13:12 UTC, chipzoller commented
No problem. If the guide isn't clear, let us know.

2024-08-02 13:19 UTC, merged