Update sample policies to include all container types in a pod. Issue reference:  #951
kyverno/policies pull request #1111
Opened 2024-08-05 20:43 UTC by dolisss

## Related Issue(s)

## Description

## Checklist

- [] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-08-05 20:46 UTC, dolisss commented
Fixes

2024-08-06 11:25 UTC, chipzoller requested changes
Tiller (Helm v2) is so old technology I don't think it's worth making this change. Would suggest focusing on more useful policies in the present.

2024-08-06 13:01 UTC, dolisss commented
I am updating all the best practice policies. Can you approve this one while I add the logic in other policies too?

2024-08-06 19:33 UTC, dolisss commented
@chipzoller  Extended the logic to the "disallow latest tag" policy along with changes needed for the chainsaw test cases.

2024-08-06 19:38 UTC, chipzoller requested changes
Missing extended tests for disallow-helm-tiller.

2024-08-06 19:45 UTC, dolisss commented
@chipzoller  thought the Helm Tiller policy was outdated and that test cases might not be necessary. However, I’ve updated them now. Please review the changes

2024-08-06 19:57 UTC, chipzoller commented
How have you tested the changes you are making in this PR?

2024-08-06 20:00 UTC, dolisss commented
I have tested this locally as well as in Kyverno Playground.Do you see any issue? Let me know..

2024-08-06 20:15 UTC, chipzoller requested changes

2024-08-06 20:15 UTC, chipzoller commented on best-practices/disallow-latest-tag/disallow-latest-tag.yaml
> +        - list: "request.object.spec.initContainers"
No containers[] any longer.

2024-08-06 20:15 UTC, chipzoller commented on best-practices/disallow-latest-tag/disallow-latest-tag.yaml
> +        - list: "request.object.spec.initContainers"
No containers[] any longer.

2024-08-06 20:15 UTC, chipzoller commented on best-practices/disallow-helm-tiller/disallow-helm-tiller.yaml
> +        - list: "request.object.spec.initContainers"
No containers[] any longer.

2024-08-06 20:15 UTC, chipzoller commented on best-practices/disallow-helm-tiller/artifacthub-pkg.yml
> +digest: 31126cee424a796fe9a4078d879a2d650fa6a3efc267d714a90a54604d91a9de
Recalculate.

2024-08-06 20:15 UTC, chipzoller commented on best-practices/disallow-latest-tag/artifacthub-pkg.yml
> +digest: 3e299e0f018ff57ee78cfff4119df58d72e11669908eff9dfe8294f3be7a6e60
Recalculate.

2024-08-06 20:56 UTC, chipzoller requested changes
Please fix failing tests. Also complete the PR template (checklist).

2024-08-07 14:43 UTC, dolisss commented
@chipzoller I tried updating the digest using my Mac, but the check failed. I reverted to the old digest, but it still didn't work. How can I generate the digest? I am using the following command.

```
 shasum -a 256 disallow-latest-tag.yaml 
2760272e57d9988ba447f62d23bba382092d00a5e14dbf00555e4170ea90593a 
```

2024-08-09 12:10 UTC, chipzoller requested changes
Digests are expected to be generated in Linux; you can see the digest expected in the Policy Test step and use that if you're unable to generate one on your own system.

Tests still need to be fixed here.

2024-08-12 20:33 UTC, dolisss commented
@chipzoller Thanks! it worked with Linux. What checks are you referring to? I don't see any on my page.

2024-08-12 20:50 UTC, chipzoller commented
Please see failing CI checks.

2024-08-14 15:07 UTC, dolisss commented
@chipzoller Please review.

2024-08-14 20:42 UTC, chipzoller approved these changes

2024-08-14 20:42 UTC, merged