Added a new policy: deny-force-delete
kyverno/policies pull request #1115
Opened 2024-08-07 03:23 UTC by fast-n-curious

## Description

When deleting any resources (Pods/ Deployments/ Services/ Cronjobs etc.), the default timer is 30 seconds which allows a graceful shutdown of the resource. The flag '--grace-period=0 --force' removes this timer and shutsdown the resource immediately. Using this flag may result in data loss as resources as the state may not be saved or lead to potential service disruption. This policy prevents any non-admins to forcefully delete any resources immediately.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-08-09 12:06 UTC, chipzoller requested changes

2024-08-09 12:06 UTC, chipzoller commented on other/deny-force-delete/.chainsaw-test/goodpod.yaml
`options` is an invalid field for Pods and all other resources. This field will only be populated in the AdmissionReview if a DELETE request is sent with a flag such as `--grace-period`. You will have to use a command/script step to perform a deletion using that flag.

2024-08-09 12:06 UTC, chipzoller commented on other/deny-force-delete/.chainsaw-test/badpod.yaml
See comments on `goodpod.yaml`.

2024-08-09 12:06 UTC, chipzoller commented on other/deny-force-delete/.kyverno-test/resource.yaml
See comments on Chainsaw test resources. The `options` field is invalid in an actual resource spec. For the Kyverno CLI, you will need to set a variable instead which looks like you're doing. All resources used in testing must be valid resources.

2024-08-14 20:01 UTC, fast-n-curious commented
@chipzoller not sure why it's not able to verify the signature. As can be seen from the below screenshot, I have reverted my previous changes and submitted them with signature again. It's still throwing an error!

<img width="1201" alt="Screenshot 2024-08-14 at 3 00 04 PM" src="https://github.com/user-attachments/assets/89df9861-05ba-4a6a-9713-7fa55f36b287">

2024-08-14 20:42 UTC, chipzoller commented
You need to sign all your commits per DCO. Please also resolve all conversations when you push changes which address them.

2024-08-26 18:22 UTC, fast-n-curious commented
Will open a new PR with the proper signature for DCO to pass.

2024-08-26 18:22 UTC, closed without merging