feat: add block velero restore example policy
kyverno/policies pull request #221
Opened 2022-01-14 20:20 UTC by andrewkaczynski

## Related issue

## Milestone of this PR

## What type of PR is this

/kind documentation

## Proposed Changes

Example policy for blocking Velero Restore operation into protected or system namespaces.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] My PR contains new or altered behavior to Kyverno and
- [x] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.

## Further Comments

2022-01-15 12:59 UTC, chipzoller commented on other/block-velero-restore/block-velero-restore.yaml
> +    policies.kyverno.io/category: Sample
Category here should be "Velero"

2022-01-15 13:00 UTC, chipzoller commented on other/block-velero-restore/block-velero-restore.yaml
> +  validationFailureAction: enforce
validationFailureAction to "audit" for sample policies

2022-01-15 13:00 UTC, chipzoller requested changes
Thank you! Just a couple minor changes for now.

2022-01-15 15:32 UTC, andrewkaczynski commented
Policy updated as per your comments. Thank you

2022-01-16 20:40 UTC, chipzoller approved these changes

2022-01-16 20:40 UTC, merged