fix unique-ingress-paths policy
kyverno/policies pull request #235
Opened 2022-01-26 09:57 UTC by vyankyGH

## Related issue
Signed-off-by: Vyankatesh vyankateshkd@gmail.com

## Related issue
closes https://github.com/kyverno/kyverno/issues/3087

## Milestone of this PR
milestone 1.6.0

## What type of PR is this
> /kind bug

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/kyverno/blob/main/CONTRIBUTING.md).
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] My PR contains new or altered behavior to Kyverno and
- [x] I have read the [PR documentation guide](https://github.com/kyverno/kyverno/blob/main/.github/pr_documentation.md) and followed the process including adding proof manifests to this PR.

## Further Comments

2022-01-26 16:27 UTC, zeborg requested changes
I feel like we should add `any`/`all` in the `preconditions` to conform to changes in #233 and avoid unresolved conditions due to the recently observed regression in k8s `1.23.0`-`1.23.2`.

Ref: https://github.com/kyverno/kyverno/issues/2978

2022-01-27 07:36 UTC, realshuting commented
Thanks @vyankyGH - can you attach different paths that you've tested?
- `/testpath`
-  `/test/path`
- `/test/path/` (not sure if this is a valid path)

2022-01-27 07:38 UTC, realshuting commented
> I feel like we should add `any`/`all` in the `preconditions` to conform to changes in #233 and avoid unresolved conditions due to the recently observed regression in k8s `1.23.0`-`1.23.2`.
> 
> Ref: [kyverno/kyverno#2978](https://github.com/kyverno/kyverno/issues/2978)

Yes, let's also update to any/all.

2022-01-29 13:05 UTC, chipzoller approved these changes

2022-01-29 13:05 UTC, merged