check annotations and paths
kyverno/policies pull request #302
Opened 2022-04-23 19:50 UTC by JimBugwadia

Signed-off-by: Jim Bugwadia <jim@nirmata.com>

Fixes https://github.com/kyverno/policies/issues/301

## Description

Sample policies to restrict NGINX Ingress annotation values and Ingress host paths

## Checklist

- [] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

2022-04-23 19:53 UTC, JimBugwadia commented
@chipzoller - did you find a good source for the host path values to restrict? 

The rules file

```	invalidEtcDir         = regexp.MustCompile(`/etc/(passwd|shadow|group|nginx|ingress-controller)`)
	invalidSecretsDir     = regexp.MustCompile(`/var/run/secrets`)

2022-04-23 20:07 UTC, chipzoller commented on best-practices/nginx_path_checks/restrict-path.yaml
> +        resources:
Let's put this under either an `any` or `all` block to be consistent with conventions.

2022-04-23 20:08 UTC, chipzoller commented on best-practices/nginx_annotation_checks/restrict-annotations.yaml
> +        resources:
Let's put this under either an `any` or `all` block to be consistent with conventions.

2022-04-23 20:10 UTC, chipzoller requested changes
Comments, plus can we add the `kyverno-version` and `kubernetes-version` annotations as documented [here](https://github.com/kyverno/policies/wiki/Kyverno-annotations)? When I wrote and tested, I did so on Kyverno 1.6.2 and Kubernetes 1.23.

2022-04-23 20:11 UTC, chipzoller commented
> @chipzoller - did you find a good source for the host path values to restrict?
> 
> The rules file has 2 checks:
> 
> https://github.com/kubernetes/ingress-nginx/blame/main/internal/ingress/inspector/rules.go
> 
> ```go
>         invalidEtcDir         = regexp.MustCompile(`/etc/(passwd|shadow|group|nginx|ingress-controller)`)
>         invalidSecretsDir     = regexp.MustCompile(`/var/run/secrets`)
> ```
> 
> So wondering if we should provide additional or limit to that.

In the path rule I just filtered for `/etc/` to make it simple. And `/var/run/secrets` is covered. Or did you mean something else?

2022-04-23 21:58 UTC, JimBugwadia commented
There are a number of other path checks at:

https://github.com/kyverno/policies/pull/302/files#diff-057a9bd58ec1015a0ead70c75ed14a6eb413c1df84a912d82ee3ad86b91ca701R25

Can we remove them, only keeping `/etc` and `var/run/secrets`?

2022-04-23 23:07 UTC, chipzoller commented
Sorry, I can't see the diff on mobile.

2022-04-24 00:11 UTC, JimBugwadia commented
Looks like some of the prior policy tests are failing:

applying 1 policy to 3 resources... 

│───│─────────────────────────────│──────────────────────────────────│─────────────────────────────────────│────────│
│ # │ POLICY                      │ RULE                             │ RESOURCE                            │ RESULT │
│───│─────────────────────────────│──────────────────────────────────│─────────────────────────────────────│────────│
│ 1 │ cert-manager-limit-duration │ certificate-duration-max-100days │ default/Certificate/letsencrypt-crt │ Fail   │
│ 2 │ cert-manager-limit-duration │ certificate-duration-max-100days │ default/Certificate/acme-crt-short  │ Pass   │
│ 3 │ cert-manager-limit-duration │ certificate-duration-max-100days │ default/Certificate/acme-crt-long   │ Pass   │
│───│─────────────────────────────│──────────────────────────────────│───────────────────────────────

There may be others...

2022-04-24 00:38 UTC, chipzoller commented
Yes, there's a CLI code regression causing this. I pointed this out a little while ago. It's not a policy problem.

2022-04-24 07:45 UTC, realshuting commented
> Yes, there's a CLI code regression causing this. I pointed this out a little while ago. It's not a policy problem.

@mritunjaysharma394 - was this related to your recent change of re-structuring CLI?

@vyankyGH  - can you help fix the CLI failure?

2022-04-24 11:32 UTC, chipzoller commented
> There are a number of other path checks at:
> 
> https://github.com/kyverno/policies/pull/302/files#diff-057a9bd58ec1015a0ead70c75ed14a6eb413c1df84a912d82ee3ad86b91ca701R25
> 
> Can we remove them, only keeping `/etc` and `var/run/secrets`?

I see the diff now. I was going by mitigation suggestion [here](https://github.com/kubernetes/ingress-nginx/issues/8502) where it says check against newly added rules or that ConfigMap list. I just combined them together to be extra safe.

2022-04-24 19:57 UTC, JimBugwadia commented
> I see the diff now. I was going by mitigation suggestion https://github.com/kubernetes/ingress-nginx/issues/8502 where it says check against newly added rules or that ConfigMap list. I just combined them together to be extra safe.

I believe that applies to annotations as well as paths. I reduced the path list to remove the annotation directives.

We can submit and get more feedback from the Kubernetes authors.

2022-04-25 12:15 UTC, chipzoller commented
From my reading of the [issue](https://github.com/kubernetes/ingress-nginx/issues/8502), which applies to both CVEs (so the path and the annotation), the same checks need to apply to both. It says rules or ConfigMap, so I just did both to be safe. 

Rules:
```
	invalidAliasDirective = regexp.MustCompile(`\s*alias\s*.*;`)
	invalidRootDirective  = regexp.MustCompile(`\s*root\s*.*;`)
	invalidEtcDir         = regexp.MustCompile(`/etc/(passwd|shadow|group|nginx|ingress-controller)`)
	invalidSecretsDir     = regexp.MustCompile(`/var/run/secrets`)
	invalidByLuaDirective = regexp.MustCompile(`.*_by_lua.*`)
```

ConfigMap:

```
"load_module,lua_package,_by_lua,location,root,proxy_pass,serviceaccount,{,},',\""
```

Maybe for the annotations policy we should add a note advising that the [ConfigMap](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#annotation-value-word-blocklist) is also recommended separately.

Also, would you mind adding those Kyverno and Kubernetes annotations showing on which versions this was successfully tested?

2022-04-25 15:54 UTC, chipzoller approved these changes

2022-04-25 15:55 UTC, merged