Exclude Policy Reporter from 'restrict-automount-sa-token' Policy
kyverno/policies pull request #348
Opened 2022-06-16 12:45 UTC by fjogeleit

Signed-off-by: Frank Jogeleit <frank.jogeleit@web.de>

## Related Issue(s)

[kyverno/policy-reporter#](https://github.com/kyverno/policy-reporter/issues/155)

## Description

Exclude Policy Reporter from Restrict SA automount policy.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

2022-06-16 12:56 UTC, chipzoller requested changes

2022-06-16 12:56 UTC, chipzoller commented on other/restrict_automount_sa_token/kyverno-test.yaml
> +    result: pass
Should be `skip`

2022-06-16 13:20 UTC, fjogeleit commented on other/restrict_automount_sa_token/kyverno-test.yaml
> +    result: pass
Updated, thanks!

2022-07-04 12:15 UTC, chipzoller approved these changes

2022-07-04 12:15 UTC, merged