add topologyspreadconstraints policy
kyverno/policies pull request #443
Opened 2022-10-30 13:27 UTC by monotek

Signed-off-by: André Bauer <andre.bauer@staffbase.com>

## Related Issue(s)

## Description
- add topologyspreadconstraints policy

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

2022-10-30 14:03 UTC, monotek commented
We might want to add a precondigtion here too:
```
      preconditions:
        all:
          - key: "{{ request.object.spec.replicas }}"
            operator: GreaterThanOrEquals
            value: 3
```

What do you think?

2022-10-30 14:28 UTC, chipzoller commented
That'd probably be a good enhancement.

2022-10-30 14:46 UTC, monotek commented
done

2022-11-01 15:58 UTC, chipzoller requested changes
Request you to rename the file `tsc-policy.yaml` to be more closely aligned with the policy name.

2022-11-01 16:00 UTC, chipzoller requested changes

2022-11-01 16:00 UTC, chipzoller commented on other/require-topologyspreadconstraints/tsc-policy.yaml
> +  name: spread-pods
Name should be updated.

2022-11-01 16:00 UTC, chipzoller commented on other/require-topologyspreadconstraints/tsc-policy.yaml
> +  annotations:
Should be annotations for min Kyverno and min K8s versions.

2022-11-01 16:00 UTC, chipzoller commented on other/require-topologyspreadconstraints/tsc-policy.yaml
> +    policies.kyverno.io/title: Spread Pods Across Nodes & Zones
Title needs update

2022-11-01 16:00 UTC, chipzoller commented on other/require-topologyspreadconstraints/tsc-policy.yaml
> +    policies.kyverno.io/description: >-
Description states 3 things:
1. What is the context
2. How does this policy add value
3. What does this policy do

2022-11-01 16:00 UTC, chipzoller commented on other/require-topologyspreadconstraints/tsc-policy.yaml
> +  failurePolicy: Ignore
Remove please. We omit this in samples.

2022-11-28 18:46 UTC, chipzoller approved these changes

2022-11-28 18:46 UTC, merged