update README.md and PR template
kyverno/policies pull request #554
Opened 2023-04-05 20:43 UTC by guohaoyu110

## Related Issue(s)
Close: https://github.com/kyverno/policies/issues/553

## Description
update readme to include artifact-pkg.yml template, artifact-pkg.yml metadata instructions and include updated PR template

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.

2023-04-05 20:49 UTC, guohaoyu110 commented
@chipzoller  updated, please review. Thank you.

2023-04-05 22:43 UTC, chipzoller requested changes

2023-04-05 22:43 UTC, chipzoller commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [] I have added artifact-pkg.yml file with the policy metadata and refer to the [template](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml)
Name is wrong.

2023-04-05 22:43 UTC, chipzoller commented on README.md
> +
Add this under a new heading called `### Artifact Hub`

2023-04-05 22:43 UTC, chipzoller commented on README.md
> +
Add a new bullet point where L30 currently is that states:

"* Create the `artifacthub-pkg.yml` file in the same directory as your policy. See the Artifact Hub section below for more details on its contents."

2023-04-05 22:43 UTC, chipzoller commented on README.md
> +
Find the appropriate bullet above in the same Contribution heading to state the following things:

1. A dedicated folder must be created for each policy.
2. The folder must be named the same as the policy.
3. Use dashes and not underscores.

2023-04-05 22:43 UTC, chipzoller commented on README.md
> +2. Add the Kyverno policy YAML file to the folder.
Eliminate and incorporate as per the above comment.

2023-04-05 22:43 UTC, chipzoller commented on README.md
> +3. Add an `artifacthub-pkg.yml` metadata file to the folder. See the [Template Policy Metadata File](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml) section for an e
Change second sentence to:

"See an example metadata file for Kyverno policies below and customize per the comments."

2023-04-05 22:43 UTC, chipzoller commented on README.md
> +# artifacthub-pkg.yml
Remove

2023-04-05 22:43 UTC, chipzoller commented on README.md
> +
Eliminate excess new lines. Only a single new line should separate code block fencing from headings.

2023-04-05 22:43 UTC, chipzoller commented on README.md
> +```
Please replace all this with one of the examples you created from the Velero folder. In addition, add to the end of each line a comment which describes what goes in each value.

2023-04-05 22:47 UTC, chipzoller commented
From the check list above:

```
All Kyverno policies must be in individual folders.
```

This is _not_ addressed in this PR. As mentioned the other day, there are many policies in the `other` folder which live outside of folders. All policies in this repo must be in dedicated folders which use dashes over underscores and where the folder is the same as the policy name.

2023-04-05 22:47 UTC, chipzoller commented
Please also go through ALL policies in this repo and ensure that the policies match the folder name. I have only pointed out two in the Kasten folder, but there may be others as I did not do this for you.

2023-04-05 22:52 UTC, chipzoller commented
Please also update the description since you are covering other tasks than just those you mentioned.

2023-04-06 00:54 UTC, guohaoyu110 commented
@chipzoller  updated all, please review. Thank you.

2023-04-06 01:34 UTC, chipzoller requested changes

2023-04-06 01:34 UTC, chipzoller commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [] I have added artifacthub-pkg.yml file with the policy metadata and refer to the [template](https://github.com/artifacthub/hub/blob/master/docs/metadata/artifacthub-pkg.yml)
"I have added the artifacthub-pkg.yml file and have verified it is complete and correct."

2023-04-06 01:34 UTC, chipzoller commented on README.md
> +1. A dedicated folder must be created for each policy.
New line always between heading and start of content.

2023-04-06 01:34 UTC, chipzoller commented on README.md
> +1. A dedicated folder must be created for each policy.
These three numbers should go above as bullets under the Contribution section.

2023-04-06 01:34 UTC, chipzoller commented on README.md
> +```yaml
Space between code blocks.

2023-04-06 01:34 UTC, chipzoller commented on README.md
> +description: >-
Please add comment here indicating the value should be taken from the relevant annotation.

2023-04-06 01:34 UTC, chipzoller commented on README.md
> +    # A short description of the package (required)
Remove

2023-04-06 01:34 UTC, chipzoller commented on README.md
> +# The SHA256 hash String that uniquely identifies this package version (optional)
Add this as on the same line as above.

2023-04-06 01:34 UTC, chipzoller commented on README.md
> +     # The installation instructions for the package (optional)
Put on same line as install.

2023-04-06 01:34 UTC, chipzoller commented on README.md
> +  # Keywords associated with the package (optional)
Move to keywords line. Keywords should always have "kyverno" and whatever the value of the value of the `policies.kyverno.io/category` annotation.

2023-04-06 01:34 UTC, chipzoller commented on README.md
> +# The README of the package (optional)
Same as previous comments.

2023-04-06 01:34 UTC, chipzoller commented on README.md
> +# The README of the package (optional)
readme should be same as `policies.kyverno.io/description` annotation plus the last sentence as a static value.

2023-04-06 01:34 UTC, chipzoller commented on README.md
> +# Annotations associated with the package (optional)
Same as previous. Tell them where to get these annotations. Point them here: https://artifacthub.io/docs/topics/annotations/kyverno/

2023-04-06 01:34 UTC, chipzoller commented on README.md
> +```
New line after code blocks.

2023-04-06 01:45 UTC, chipzoller commented
And you still have not addressed the second checkbox "All folders contain policies with the same name."

2023-04-06 10:23 UTC, guohaoyu110 commented
@chipzoller   please review, thank you.

2023-04-06 15:11 UTC, chipzoller requested changes

2023-04-06 15:11 UTC, chipzoller commented on README.md
> +
Remove excess empty lines.

2023-04-06 15:11 UTC, chipzoller commented on README.md
> +keywords: # Keywords should always have "kyverno" and whatever the value of the value of the policies.kyverno.io/category annotation. (optional)
Duplicate "the value"

2023-04-06 17:03 UTC, guohaoyu110 commented
@chipzoller ok.

2023-04-06 22:15 UTC, chipzoller requested changes
In addition to these last few changes, I find that you still have not located and changed all policies to have names equal to their folders. One such example in /other/concatenate-configmaps

2023-04-06 22:15 UTC, chipzoller commented on README.md
> +description: >-
Please add the actual description here just like you've done below for the `readme` field.

2023-04-06 22:15 UTC, chipzoller commented on README.md
> +annotations: # Annotations values should be the same as policies.kyverno.io annotations and get annotations from https://artifacthub.io/docs/topics/annotations/kyverno/
Change comment to:

"See the annotations guide on Artifact Hub here: https://artifacthub.io/docs/topics/annotations/kyverno/"

2023-04-06 23:19 UTC, guohaoyu110 commented
> In addition to these last few changes, I find that you still have not located and changed all policies to have names equal to their folders. One such example in /other/concatenate-configmaps

This is the script i write. I am pretty sure this time I have checked all the folders and yaml files. 

#!/bin/bash

# 遍历当前目录下的所有子文件夹
for dir in */; do
    # 获取文件夹名称
    folder_name=$(basename "$dir")

    # 构建预期的 .yaml 文件名
    yaml_file="${dir}${folder_name}.yaml"

    # 检查文件是否存在
    if [ -e "$yaml_file" ]; then
        echo "pass"
    else
        echo "In ${dir} cannot find the same name .yaml file"
    fi
done

2023-04-06 23:21 UTC, guohaoyu110 commented
@chipzoller  please check, thank you so much.

2023-04-07 12:08 UTC, chipzoller approved these changes
Looks good.

2023-04-07 12:08 UTC, merged