Added policy - block-cluster-admin-from-ns.yaml
kyverno/policies pull request #601
Opened 2023-05-08 12:28 UTC by tommeramber

## Related Issue(s)
[x]

## Description
In this policy, I’ve told `Kyverno` to look for all user operations (`CREATE, UPDATE, DELETE`), on every object kind, in the testnamespace namespace, and for the `clusterRole cluster-admin`. I’ve also added the `subject User testuser` so it won’t include all the cluster-admins in the cluster.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2023-05-08 14:57 UTC, chipzoller requested changes
Thanks for this! In addition to comments, couple things we need:

1.) Annotations. All Kyverno policies must have a full set of annotations. See the wiki here for details.
2.) Artifact Hub. Policies need the AH metadata file. See https://github.com/kyverno/policies#artifact-hub.

2023-05-18 09:28 UTC, tommeramber commented on other/block-cluster-admin-from-ns/block-cluster-admin-from-ns.yaml
> +  validationFailureAction: enforce
Done!

2023-05-18 09:35 UTC, tommeramber reviewed
Please notify me if anything else is required

2023-06-01 15:29 UTC, chipzoller commented
Looks like DCO sign-off is still missing.

2023-06-07 23:28 UTC, chipzoller commented
@tommeramber DCO sign-off is still required here.

2023-06-12 11:59 UTC, tommeramber commented
@chipzoller Done :)

2023-06-13 18:35 UTC, chipzoller approved these changes

2023-06-13 19:11 UTC, merged