Put 'Validate all policies' before 'Test Policy'
kyverno/policies pull request #616
Opened 2023-05-18 00:56 UTC by guohaoyu110

## Related Issue(s)
Close: https://github.com/kyverno/policies/issues/611

## Description

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2023-05-18 01:13 UTC, guohaoyu110 commented
@chipzoller  completed. 
add ignore to the pod-security/enforce/kustomization.yaml

2023-05-21 21:06 UTC, chipzoller requested changes

2023-05-21 21:06 UTC, chipzoller commented on .github/workflows/ci.yml
> +        uses: actions/checkout@v2
Do not change the checkout version here.

2023-05-21 21:06 UTC, chipzoller commented on .github/workflows/ci.yml
> +          ignore_dir="$GITHUB_WORKSPACE/pod-security/enforce"
This isn't what I meant. We don't want to ignore a specific directory, we want to exempt any file named `kustomization.yaml`, regardless of where it's located, from being caught by this logic.

2023-05-22 07:12 UTC, guohaoyu110 commented
@chipzoller  could you please review this updated logic?

2023-05-22 18:58 UTC, chipzoller approved these changes

2023-05-22 18:58 UTC, chipzoller commented
Thank you. Once this is merged, please send 3 PRs, each triggering a "bad" result as previously discussed.

2023-05-22 18:58 UTC, merged

2023-05-22 18:59 UTC, guohaoyu110 commented
> Thank you. Once this is merged, please send 3 PRs, each triggering a "bad" result as previously discussed.

know, will add today.