fix: require-storageclass policy
kyverno/policies pull request #618
Opened 2023-05-19 03:04 UTC by joebowbeer

## Related Issue(s)

Fixes #617 

## Description

Enhance Require StorageClass policy to only require storageClassName if the StatefulSet has volumeClaimTemplates.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2023-05-23 00:41 UTC, joebowbeer commented
@chipzoller please take a look

2023-05-24 11:32 UTC, chipzoller requested changes
Thanks for this. As one last step, please calculate the new sha256 sum for the policy file and update this in `artifact-hub.pkg` file so the changes may be picked up and displayed in Artifact Hub.

2023-05-24 15:24 UTC, joebowbeer commented
@chipzoller I was wondering what that file was for 😄

Information about the digest is well hidden. I assume this snippet is what is needed:

https://github.com/kyverno/policies/pull/597#issuecomment-1532230662

I suggest adding this as a validation check, similar to DCO. When it fails, the submitter can copy the expected digest from the failure message and paste it into their PR.

2023-05-24 16:40 UTC, joebowbeer commented
@chipzoller PTAL

2023-05-26 23:29 UTC, chipzoller approved these changes
Thanks for your work here!

2023-05-26 23:29 UTC, merged