Add add-karpenter-daemonset-priority-class
kyverno/policies pull request #631
Opened 2023-06-02 07:19 UTC by wdonne

## Description

When a DaemonSet is added to a cluster every node will get a new pod. There may not be enough room for this on every node. Karpenter cannot provision extra nodes just for the DaemonSet because the new pods are not scheduled the way regular pods are. It would require parallel scheduling logic that is not proper to Kubernetes. Therefore, eviction of regular pods should happen instead. This can be achieved with the priority class system-node-critical.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2023-06-02 22:15 UTC, wdonne commented
There is a test that fails for a strange reason. It says that the subfolder "test1" doesn't contain a YAML file with the same name as the directory plus extension. I understand that this is the case for a policy file, but my subfolders are there to host multiple tests for the same policy. With the CLI this works fine. Is there a way I can put all the tests in the same folder? As far as I can see there can only be one `kyverno-test.yaml` file and I don't see how the four tests can be hosted by it.

2023-06-03 16:25 UTC, mintbomb27 commented
@wdonne You can put all your pods in a single `resource.yaml` and then validate based on the resource name, using a single `kyverno-test.yaml`. Please find an example [here](https://github.com/kyverno/policies/tree/055cd81a7de52d66e9783bd2279854aa468d4f9a/best-practices/add-safe-to-evict).

2023-06-04 07:43 UTC, wdonne commented
@mintbomb27 Thanks for your reply. I have updated the PR accordingly.

2023-06-05 22:02 UTC, chipzoller requested changes
Thanks for the PR. Just a couple minor changes.

2023-06-06 08:53 UTC, wdonne commented on karpenter/add-karpenter-daemonset-priority-class/add-karpenter-daemonset-priority-class.yaml
> +    policies.kyverno.io/category: Karpenter, EKS Best Practices
That is not yet in the Best Practices guide. It came from this discussion: https://github.com/aws/karpenter/issues/3256. I'll remove it.

2023-06-06 12:14 UTC, wdonne commented on karpenter/add-karpenter-daemonset-priority-class/artifacthub-pkg.yml
> +readme: >-
I have fixed it.

2023-06-06 12:15 UTC, wdonne commented on karpenter/add-karpenter-daemonset-priority-class/daemonset.yaml
I have fixed it.

2023-06-07 22:08 UTC, chipzoller approved these changes
Thanks for the contributions!

2023-06-07 23:29 UTC, merged

2023-06-08 06:44 UTC, wdonne commented
With pleasure!