tests: best-practices tests
kyverno/policies pull request #633
Opened 2023-06-03 16:12 UTC by mintbomb27

## Related Issue(s)

## Description

Tests for:

- [x] restrict-service-external-ips
- [x] restrict-node-port
- [x] restrict-image-registries
- [x] require-pod-requests-limits
- [x] require-probes
- [x] restrict-ro-rootfs
- [x] require-labels
- [x] require-drop-cap-net-raw
- [x] require-drop-all
- [x] disallow-latest-tag
- [x] disallow-helm-tiller
- [x] disallow-empty-ingress-host
- [x] disallow-default-namespace
- [x] disallow-cri-sock-mount

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [ ] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2023-06-05 11:07 UTC, chipzoller commented
Is this PR ready for review?

2023-06-05 12:08 UTC, chipzoller commented on best-practices/disallow-helm-tiller/02-manifests.yaml
Same situation here as the previous comment. What about if a Pod has two containers where one is "good" and the other is "bad"? The entire Pod must be rejected at that point. You could even forego the simpler version of these tests in favor of the 2-container examples if you wanted. But, as I said, tests like this are critical. Far too often we have _thought_ that code worked but it turns out it didn't because we were only testing situations where a given resource had only one "thing" which was being validated. We will not make that mistake going forward.

2023-06-05 12:12 UTC, chipzoller commented on best-practices/require-drop-all/02-manifests.yaml
Ditto again. You can borrow test resources I wrote here: https://github.com/kyverno/policies/blob/main/pod-security/restricted/disallow-capabilities-strict/resource.yaml

2023-06-05 12:12 UTC, chipzoller commented on best-practices/require-drop-cap-net-raw/02-manifests.yaml
Ditto to above.

2023-06-05 12:14 UTC, chipzoller commented on best-practices/require-labels/02-manifests.yaml
Since auto-gen is going to be active for this one, we should ensure at least one resource from each class (Pod, Deployment, CronJob) is also being tested.

2023-06-05 12:15 UTC, chipzoller commented on best-practices/require-pod-requests-limits/02-manifests.yaml
Similar comment as those above. What if a Pod has two containers where one is fully compliant and the other is not?

2023-06-05 12:21 UTC, chipzoller commented on best-practices/require-probes/02-manifests.yaml
Also, auto-gen. And also, it would be good to test the UPDATE side of this policy: What happens when there's a compliant Pod (which passed the policy) and then it is subsequently updated to add a new container which is not compliant. Is the update blocked?

2023-06-05 12:23 UTC, chipzoller commented on best-practices/require-ro-rootfs/02-manifests.yaml
Auto-gen

2023-06-05 12:25 UTC, chipzoller commented on best-practices/restrict-image-registries/02-manifests.yaml
On this test, let's also test for the ephemeralContainers. If you haven't used this before, we'll be doing a `kubectl debug` along with an in-line Pod definition to add a non-compliant ephemeral container.

2023-06-05 13:03 UTC, mintbomb27 commented on best-practices/add-safe-to-evict/02-manifests.yaml
Okay. Adding it.

2023-06-05 13:10 UTC, mintbomb27 commented on best-practices/disallow-cri-sock-mount/good-pod.yaml
Done!

2023-06-05 13:20 UTC, mintbomb27 commented on best-practices/disallow-helm-tiller/02-manifests.yaml
Got that.

2023-06-05 19:35 UTC, mintbomb27 commented on best-practices/require-drop-all/02-manifests.yaml
Should I cover the Pod, CronJob, and Deployment here as well?

2023-06-05 19:36 UTC, chipzoller commented on best-practices/require-drop-all/02-manifests.yaml
It's a good idea. Basically, any policy where auto-gen is enabled (even if selectively enabled) we should try and have one test resource per auto-generated rule.

2023-06-05 20:04 UTC, mintbomb27 commented on best-practices/require-drop-all/02-manifests.yaml
How do we figure if auto-gen is enabled?

2023-06-05 21:54 UTC, chipzoller commented on best-practices/require-drop-all/02-manifests.yaml
Give [the docs](https://kyverno.io/docs/writing-policies/autogen/) a read for starters, then as you develop these tests and create the policies, get the policy back and inspect the YAML. You should see, if auto-gen is active, additional rules created under the `status` object.

2023-06-06 11:38 UTC, mintbomb27 commented on best-practices/require-probes/02-manifests.yaml
For some reason, this doesn't auto-gen a rule for a Job, or CronJob.

2023-06-06 11:53 UTC, chipzoller commented on best-practices/require-probes/02-manifests.yaml
Yes, because it has the auto-gen override annotation set: `pod-policies.kyverno.io/autogen-controllers: DaemonSet,Deployment,StatefulSet`

2023-06-06 11:54 UTC, mintbomb27 commented on best-practices/require-probes/02-manifests.yaml
Woah. Just saw that.

2023-06-06 17:48 UTC, chipzoller requested changes
Looks great! Only a small nit regarding the UPDATE test.

2023-06-06 17:48 UTC, chipzoller commented on best-practices/require-probes/bad-pod-update.yaml
This update would be invalid. A container name may not be changed and two containers in the same Pod cannot have the same name. Your update test here should only try and add a second container (with a different name) to the existing Pod but with no probes defined.

2023-06-06 17:48 UTC, chipzoller commented on best-practices/require-probes/good-pods.yaml
> +      periodSeconds: 20
I would also just choose one probe here and not all 3 as it's unrealistic, but nevertheless still works.

2023-06-06 18:25 UTC, merged