tests: kubecost, linkerd, nginx tests
kyverno/policies pull request #642
Opened 2023-06-12 14:26 UTC by mintbomb27

## Related Issue(s)

## Description
Contains 12 kuttl tests for KubeCost(2), Linkerd(7), Nginx-Ingress(3) Policies.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [ ] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2023-06-12 17:06 UTC, chipzoller commented
I see a failure in /istio/create-authorizationpolicy. You may need to add a `sleep 3` statement after creating the ClusterRole to give Kyverno a bit more time to pick up the permissions.

2023-06-12 17:07 UTC, chipzoller commented
Let me know when ready for final review.

2023-06-12 17:55 UTC, chipzoller commented
Ok, try specifying the Istio one in GVK format.

2023-06-13 12:43 UTC, chipzoller requested changes
Nice work! One very minor permissions update and that's all.

2023-06-13 13:07 UTC, mintbomb27 commented on temp.json
Really sorry. That was to force delete a namespace. Removing it.

2023-06-13 13:08 UTC, mintbomb27 commented on kubevirt/add-services/01-clusterrole.yaml
> +  - "*"
Got it! Changing.

2023-06-13 14:53 UTC, chipzoller approved these changes

2023-06-13 14:53 UTC, merged