tests: 10 tests from other category
kyverno/policies pull request #649
Opened 2023-06-14 17:42 UTC by mintbomb27

## Related Issue(s)
#546 

## Description
Contains 10 new kuttl tests from others category.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [ ] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2023-06-15 20:29 UTC, chipzoller reviewed
Looks good, just one thing.

2023-06-16 04:33 UTC, mintbomb27 commented on other/add-certificates-volume/pod-resources.yaml
> +    inject-certs: enabled
```sh
case.go:369: admission webhook "mutate.kyverno.svc-fail" denied the request: mutation policy add-certificates-volume error: failed to apply policy add-certificates-volume rules [add-ssl-certs: failed to evaluate preconditions: failed to substitute variables in condition key: failed to resolve request.object.metadata.annotations."inject-certs" at path : JMESPath query failed: Unknown key "annotations" in path]```

It breaks! Can't believe I didn't try that out.

2023-06-16 04:35 UTC, mintbomb27 commented on other/add-certificates-volume/pod-resources.yaml
> +    inject-certs: enabled
Both, if it doesn't have an `inject-certs` annotation, or if it doesn't have any annotations at all, it breaks.

2023-06-16 11:28 UTC, chipzoller commented on other/add-certificates-volume/pod-resources.yaml
> +    inject-certs: enabled
Right, that's as I suspected. We need to add an [existence check](https://kyverno.io/docs/writing-policies/jmespath/#non-existence-checks) to the policy. You then need to test for that with one or two more test resources.

2023-06-16 17:00 UTC, mintbomb27 commented on other/add-certificates-volume/pod-resources.yaml
> +    inject-certs: enabled
Fixed!

2023-06-17 02:38 UTC, chipzoller requested changes
Thanks for adding this. Just need to use empty string (`''` or `""` in this case) rather than space.

2023-06-17 02:38 UTC, chipzoller commented on other/add-certificates-volume/add-certificates-volume.yaml
> +      - key: '{{request.object.metadata.annotations."inject-certs" || " "}}'
Empty string, please, not space.

2023-06-17 06:20 UTC, mintbomb27 commented on other/add-certificates-volume/add-certificates-volume.yaml
> +      - key: '{{request.object.metadata.annotations."inject-certs" || " "}}'
Fixed.

2023-06-17 11:31 UTC, chipzoller approved these changes
Thanks, looks good.

2023-06-17 11:31 UTC, merged