test: 6 c tests from others
kyverno/policies pull request #659
Opened 2023-06-22 20:50 UTC by mintbomb27

## Related Issue(s)
#546 

## Description
Contains 6 more tests covering all tests starting with c except `check-subjectaccessreview`.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [ ] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2023-06-26 00:00 UTC, chipzoller requested changes

2023-06-26 13:41 UTC, mintbomb27 commented on other/check-subjectaccessreview/02-setup-user.yaml
Sure! Will do that. And yes, will make it more generic.

2023-06-26 13:42 UTC, mintbomb27 commented on other/check-subjectaccessreview/policy-ready.yaml
Sorry! Will delete that.

2023-06-26 16:41 UTC, mintbomb27 commented on other/check-serviceaccount/01-assert.yaml
I changed the match clause to this and the `badpod01` passed.
```yaml

      match:
        any:
        - resources:
            kinds:
            - Pod
          subjects:
          - kind: ServiceAccount
            name: "?*"
            namespace: "*"
```

2023-06-26 16:42 UTC, mintbomb27 commented on other/check-env-vars/pods-bad.yaml
Done!

2023-06-26 16:51 UTC, chipzoller commented on other/check-serviceaccount/01-assert.yaml
What if the `namespace` field is omitted?

2023-06-26 16:56 UTC, mintbomb27 commented on other/check-serviceaccount/01-assert.yaml
The `name` as well as the `namespace` field are both required.

2023-06-26 17:01 UTC, chipzoller commented on other/check-serviceaccount/01-assert.yaml
Maybe try `"?*"` in there?

2023-06-26 17:21 UTC, mintbomb27 commented on other/check-serviceaccount/01-assert.yaml
No change, same result.

2023-06-26 17:33 UTC, chipzoller commented on other/check-serviceaccount/01-assert.yaml
Can you post in the kyverno channel on Kubernetes Slack with a reproduction? Would like to see why this isn't working.

2023-06-26 19:52 UTC, mintbomb27 commented on other/check-serviceaccount/01-assert.yaml
I'm not sure how this should be working? Are wildcards allowed in `subjects`?

2023-06-26 20:01 UTC, mintbomb27 commented on other/check-serviceaccount/01-assert.yaml
https://kubernetes.slack.com/archives/CLGR9BJU9/p1687809575945679

2023-06-27 11:06 UTC, mintbomb27 commented on other/check-serviceaccount/01-assert.yaml
What should I do about this? Just let it be?

2023-06-27 11:11 UTC, chipzoller commented on other/check-serviceaccount/01-assert.yaml
Yes, just leave this as-is.

2023-06-27 11:13 UTC, chipzoller approved these changes

2023-06-27 11:18 UTC, merged