test: 5 tests from others
kyverno/policies pull request #676
Opened 2023-07-04 17:19 UTC by mintbomb27

## Related Issue(s)

## Description
Contains 5 tests from others category, a minor change to `expiration-for-policyexceptions`, and installs Kyverno CLI in workflow for future jmesPath queries.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2023-07-05 10:08 UTC, mintbomb27 commented
TODO: `limit-configmap-for-sa` AH update, Policy Change if required.

2023-07-07 00:03 UTC, chipzoller requested changes
Nice work again. Several comments and suggestions.

2023-07-07 00:03 UTC, chipzoller commented on other/namespace-inventory-check/resource-check.sh
I think this would be way easier with the kyverno CLI and a JMESPath query, but if this works then great.

2023-07-07 04:13 UTC, mintbomb27 commented on .github/workflows/test.yml
> +          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
So there is a kubectl that comes with the runner I guess of the version 1.27. I realized that `curl` command did nothing as I wanted to install that specific kubectl of that kubernetes version. If we install it only we can use that the one that's curled. I saw a warning which said the skew of server and client version is greater than +/- 1. That's when I noticed it.

2023-07-07 04:24 UTC, chipzoller commented on .github/workflows/test.yml
> +          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
Ok, that's actually a good point. We should be fetching the correct version of `kubectl` according to the version of the test cluster we bring up, and then only use that for tests.

2023-07-07 04:30 UTC, mintbomb27 commented on .github/workflows/test.yml
> +          tar -xvf kyverno-cli_v1.10.0_linux_x86_64.tar.gz
I'll fetch the latest tag and download it then.

2023-07-07 04:30 UTC, mintbomb27 commented on other/inject-sidecar-deployment/01-policy.yaml
> +- inject-sidecar-deployment.yaml
Sure!

2023-07-07 04:34 UTC, mintbomb27 commented on other/inspect-csr/03-assert.yaml
> +#   name: cpol-require-authorizationpolicies
Nope, will remove.

2023-07-07 04:35 UTC, mintbomb27 commented on other/kubernetes-version-check/03-check.yaml
Thanks!

2023-07-07 04:43 UTC, mintbomb27 commented on other/ingress-host-match-tls/ingress-good.yaml
Added.

2023-07-07 04:49 UTC, mintbomb27 commented on other/inject-sidecar-deployment/deploy.yaml
Done!

2023-07-07 04:52 UTC, mintbomb27 commented on other/label-existing-namespaces/02-ns.yaml
Made the change.

2023-07-07 05:01 UTC, mintbomb27 commented on other/label-nodes-cri/label-check.sh
Made the change.

2023-07-07 05:08 UTC, mintbomb27 commented on other/limit-containers-per-pod/01-enforce.yaml
> +    sed 's/validationFailureAction: audit/validationFailureAction: Enforce/' limit-containers-per-pod.yaml | kubectl create -f -
Yes, it works without the three rules. Autogen takes care of it. And yup, fixed the operations inconsistency.

2023-07-07 05:10 UTC, mintbomb27 commented on other/limit-hostpath-vols/pod-good.yaml
Added.

2023-07-07 05:15 UTC, mintbomb27 commented on other/memory-requests-equal-limits/01-enforce.yaml
> +    sed 's/validationFailureAction: audit/validationFailureAction: Enforce/' memory-requests-equal-limits.yaml | kubectl create -f -
Yes, they work with autogen! Made the change.

2023-07-07 05:18 UTC, mintbomb27 commented on other/memory-requests-equal-limits/pod-bad.yaml
> +        memory: "150Mi"
Added.

2023-07-07 06:59 UTC, mintbomb27 commented on .github/workflows/test.yml
> +          sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
Yup, that install line does that.

2023-07-07 07:00 UTC, mintbomb27 commented on other/mutate-pod-binding/01-label-nodes.yaml
That's a pretty good idea. I'll try it out.

2023-07-07 07:02 UTC, mintbomb27 commented on other/mutate-pod-binding/05-reset.yaml
> +    kubectl get configmap -n kyverno kyverno -o yaml | sed 's/\[SelfSubjectAccessReview,\*,\*\]/\[SelfSubjectAccessReview,\*,\*\] \[Binding,\*,\*\] \[Pod\/binding,\*,\*\]/g' - | kubectl apply -f -
So I just wanted to match something and add it the same place it was there.

2023-07-07 07:04 UTC, mintbomb27 commented on other/namespace-inventory-check/resource-check.sh
How? It is already using the Kyverno CLI and JP query. But there are multiple testcases, that's all. That's why the for loop.

2023-07-09 01:35 UTC, chipzoller commented on other/namespace-inventory-check/resource-check.sh
Ok, no problem.

2023-07-09 01:35 UTC, chipzoller commented on other/mutate-pod-binding/05-reset.yaml
> +    kubectl get configmap -n kyverno kyverno -o yaml | sed 's/\[SelfSubjectAccessReview,\*,\*\]/\[SelfSubjectAccessReview,\*,\*\] \[Binding,\*,\*\] \[Pod\/binding,\*,\*\]/g' - | kubectl apply -f -
Ok

2023-07-09 01:35 UTC, chipzoller commented
Thank you for being diligent about resolving conversations as changes are pushed. This greatly helps with organization.

2023-07-09 01:46 UTC, chipzoller approved these changes
Nice work, @mintbomb27!

2023-07-09 01:46 UTC, merged