test: 5 tests from others
kyverno/policies pull request #682
Opened 2023-07-13 18:32 UTC by mintbomb27

## Related Issue(s)
#546 

## Description
Contains 5 kuttl tests from others category

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [ ] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2023-07-15 07:56 UTC, chipzoller requested changes
Nice. Couple of requests.

2023-07-15 07:56 UTC, chipzoller commented on other/require-imagepullsecrets/pod-good.yaml
Please incorporate quay.io into at least one good Pod.

2023-07-15 07:56 UTC, chipzoller commented on other/require-netpol/netpol.yaml
I'd like to see one possibly two more NetworkPolicies as part of this test in which the labels map has more than just one entry. We want to stress test the `label_match()` filter well and I think in previous tests I've seen those tests have been fairly basic. Let's bolster it here.

2023-07-17 20:49 UTC, mintbomb27 commented on other/require-netpol/netpol.yaml
Roger that.

2023-07-19 11:01 UTC, chipzoller approved these changes

2023-07-19 11:02 UTC, merged