changed other to Other
kyverno/policies pull request #865
Opened 2023-12-27 10:06 UTC by swastik959

## Related Issue(s)
fixes #862 

## Description
changed other to Other

## Checklist

- [] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2023-12-27 12:56 UTC, chipzoller requested changes
Thank you for your contribution. Please see the [contribution guide](https://github.com/kyverno/policies#contribution), specifically the points about changing the `artifacthub-pkg.yaml` file when policies are changed.

2023-12-27 12:56 UTC, chipzoller commented on .github/ISSUE_TEMPLATE/sample_policy.yml
This is not a policy and should not be changed.

2023-12-28 06:17 UTC, swastik959 commented
@chipzoller please review it now

2023-12-28 21:03 UTC, chipzoller requested changes
You only updated a single policy's corresponding `artifacthub-pkg.yml` file. Every one must be updated for each policy being updated.

2023-12-29 08:12 UTC, swastik959 commented
@chipzoller done

2023-12-29 12:44 UTC, chipzoller requested changes

2023-12-29 13:03 UTC, chipzoller commented on other/block-cluster-admin-from-ns/artifacthub-pkg.yml
> +  policies.kyverno.io/category: Other
`kyverno/category`

2023-12-29 14:20 UTC, swastik959 commented
@chipzoller please check it now

2023-12-30 13:31 UTC, chipzoller approved these changes

2023-12-30 13:31 UTC, merged