added the policy to check reference for secret in svcaccount
kyverno/policies pull request #880
Opened 2024-01-07 09:25 UTC by swastik959

## Related Issue(s)
closes #819 

## Description

## Checklist

- [] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-01-07 09:28 UTC, swastik959 commented
@chipzoller I have made a pr . though the kyverno tests were passing I am not sure why the chainsaw tests is failing . first when I ran it the error was . ``=== ERROR
        actual resource not found
`` and when I ran it second time the error has become ``  === STDERR
        Error from server (AlreadyExists): error when creating "STDIN": clusterpolicies.kyverno.io "check-service-accounts" already exists
``

2024-01-07 11:42 UTC, swastik959 commented
@chipzoller The ci for  imagepull policy is failing somehow even though it is unchanged

2024-01-10 04:36 UTC, swastik959 commented
@chipzoller please review this pr

2024-01-10 13:14 UTC, chipzoller requested changes
Missing the following annotations:

`kyverno.io/kubernetes-version`
`kyverno.io/kyverno-version`

2024-01-10 13:14 UTC, chipzoller commented on other/check-service-account/check-service-account.yaml
> +        message: "long lived API tokens are not allowed"
```suggestion
        message: "Long-lived API tokens are not allowed."
```

2024-01-10 13:14 UTC, chipzoller commented on other/check-service-account/check-service-account.yaml
> +  validationFailureAction: Enforce
```suggestion
  validationFailureAction: Audit
```

2024-01-10 13:14 UTC, chipzoller commented on other/check-service-account/check-service-account.yaml
> +
Eliminate excess new line.

2024-01-10 13:14 UTC, chipzoller commented on other/check-service-account/check-service-account.yaml
> +
Eliminate excess new line. Only one new line at the end of a file.

2024-01-10 13:14 UTC, chipzoller commented on other/check-service-account/check-service-account.yaml
> +    policies.kyverno.io/title: Check Exisitence of Secrets Reference in ServiceAccount
```suggestion
    policies.kyverno.io/title: Check Long-Lived Secrets in ServiceAccounts
```

2024-01-10 13:14 UTC, chipzoller commented on other/check-service-account/check-service-account.yaml
> +    policies.kyverno.io/category: Sample
```suggestion
    policies.kyverno.io/category: Security
```

2024-01-10 16:12 UTC, swastik959 commented
@chipzoller done

2024-01-13 13:15 UTC, chipzoller requested changes
I also think the title of this policy "check-service-accounts" (note how the name is accounts plural but account singular in the file name) is too generic and could be renamed to something more descriptive. This renaming would entail changing the folder name and all test files to match.

2024-01-13 13:15 UTC, chipzoller commented on other/check-service-account/artifacthub-pkg.yaml
> +  kyverno/kubernetesVersion: "1.21"
```suggestion
  kyverno/kubernetesVersion: "1.27"
```

2024-01-13 13:15 UTC, chipzoller commented on other/check-service-account/artifacthub-pkg.yaml
> +  kyverno/category: "Sample"
```suggestion
  kyverno/category: "Security"
```

2024-01-15 14:25 UTC, swastik959 commented
@chipzoller any update on the pr ?

2024-01-16 17:49 UTC, chipzoller commented
Please look through the current state of this PR to ensure that everything is correct and consistent, especially with respect to policy annotations and the Artifact Hub metadata file.

2024-03-02 15:06 UTC, chipzoller commented on other/check-serviceaccount-secrets/artifacthub-pkg.yaml
> +createdAt: "2024-01-06T20:14:33.000Z"
```suggestion
createdAt: "2024-03-02T06:14:33.000Z"
```

2024-03-02 15:06 UTC, chipzoller commented on other/check-serviceaccount-secrets/artifacthub-pkg.yaml
> +  kubectl apply -f https://raw.githubusercontent.com/kyverno/policies/main/other/check-service-account/check-service-account.yaml
```suggestion
  kubectl apply -f https://raw.githubusercontent.com/kyverno/policies/main/other/check-serviceaccount-secrets/check-serviceaccount-secrets.yaml
```

2024-03-02 15:07 UTC, chipzoller commented on other/check-serviceaccount-secrets/.chainsaw-test/chainsaw-test.yaml
> +          sed 's/validationFailureAction: audit/validationFailureAction: Enforce/' ../check-serviceaccount-secrets.yaml | kubectl create -f -
```suggestion
          sed 's/validationFailureAction: Audit/validationFailureAction: Enforce/' ../check-serviceaccount-secrets.yaml | kubectl create -f -
```

2024-03-02 15:08 UTC, chipzoller commented on other/check-serviceaccount-secrets/.chainsaw-test/bad-svc-account.yaml
> +  uid: f23fd170-66f2-4697-b049-e1e266b7f835
```suggestion
```

2024-03-02 15:09 UTC, chipzoller commented on other/check-serviceaccount-secrets/.chainsaw-test/bad-svc-account.yaml
> +      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"example-automated-thing","namespace":"examplens"}}
```suggestion
```

2024-03-02 15:10 UTC, chipzoller approved these changes

2024-03-02 15:21 UTC, merged