Added replace image registry with harbor
kyverno/policies pull request #890
Opened 2024-01-18 18:49 UTC by siddhikhapare

## Related Issue(s)
#882 

## Description
Rewrite the image registry, to force all pulls through a proxy cache with using harbor

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-01-19 09:06 UTC, siddhikhapare commented
@chipzoller Please review my PR.

2024-02-03 18:12 UTC, chipzoller requested changes

2024-02-03 18:12 UTC, chipzoller commented on other/replace-image-registry-with-harbor/replace-image-registry-with-harbor.yaml
> +              - Pod
Indentation is wrong here

2024-02-04 16:30 UTC, siddhikhapare commented on other/replace-image-registry-with-harbor/replace-image-registry-with-harbor.yaml
> +              - Pod
I will update it. Thanks.

2024-03-02 21:52 UTC, chipzoller commented
Significant changes were need here so I have taken this over.

2024-03-02 22:05 UTC, chipzoller commented
Need to fix a couple of CLI tests now the `--registry` flag has been added. Will do shortly.

2024-03-03 00:07 UTC, chipzoller approved these changes

2024-03-03 00:07 UTC, merged