Add disallow-proc-self-fd-workingdir.yaml (CVE-2024-21626)
kyverno/policies pull request #898
Opened 2024-02-02 19:18 UTC by lobuhi

Mitigation for CVE-2024-21626

## Related Issue(s)

## Description

## Checklist

- [] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-02-02 19:28 UTC, chipzoller requested changes
Please follow contribution guidelines in the PR template. An Artifact Hub metadata file, minimally, is required along with this PR.

2024-02-02 19:28 UTC, chipzoller commented on other/disallow-proc-self-fd-workingdir/disallow-proc-self-fd-workingdir.yaml
> +              - =(workingDir): "!/proc/self/fd*"
These all need anchors.

2024-02-02 19:28 UTC, chipzoller commented on other/disallow-proc-self-fd-workingdir/disallow-proc-self-fd-workingdir.yaml
> +        resources:
`any` block required

2024-02-02 20:42 UTC, lobuhi commented on other/disallow-proc-self-fd-workingdir/disallow-proc-self-fd-workingdir.yaml
> +              - =(workingDir): "!/proc/self/fd*"
Anchors added

2024-02-02 20:42 UTC, lobuhi commented on other/disallow-proc-self-fd-workingdir/disallow-proc-self-fd-workingdir.yaml
> +        resources:
Any block added

2024-02-03 13:00 UTC, chipzoller commented on other/disallow-proc-self-fd-workingdir/disallow-proc-self-fd-workingdir.yaml
> +              - <<: *customCheckAnchor
Sorry I wasn't clear on the anchors. I didn't mean traditional YAML anchors. The previous version of this was fine, but you'll need[ equality anchors](https://kyverno.io/docs/writing-policies/validate/#anchors) around `initContainers` and `ephemeralContainers` because a Pod may not have those and so the policy would fail for such Pods.

2024-02-03 13:00 UTC, chipzoller commented on other/disallow-proc-self-fd-workingdir/artifacthub-pkg.yml
> +  kyverno/category: "Runc"
```suggestion
  kyverno/category: "Security"
```

2024-02-05 16:48 UTC, popeyeinit commented on other/disallow-proc-self-fd-workingdir/disallow-proc-self-fd-workingdir.yaml
> +              - <<: *customCheckAnchor
Like this?
```yaml
            containers:
              - =(workingDir): "!/proc/self/fd*"
            =(initContainers):
              - =(workingDir): "!/proc/self/fd*"
            =(ephemeralContainers):
              - =(workingDir): "!/proc/self/fd*"
 ```

2024-02-08 15:35 UTC, chipzoller commented
> I think the policy is not sufficient to prevent an attack, because the [WORKDIR](https://docs.docker.com/engine/reference/builder/#workdir) may be specified in the container image and not in the k8s manifest.

That's true and this should probably be specified in the description of the policy.

2024-02-08 16:05 UTC, popeyeinit commented
> The WORKDIR instruction can resolve environment variables previously set using ENV. You can only use environment variables explicitly set in the Dockerfile.

And if I interpret the [docker docs](https://docs.docker.com/engine/reference/builder/#workdir) correctly, the `WORKDIR` maybe specified also via environment variables, so the policy should also match on that in k8s manifests?
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
spec:
  containers:
  - name: envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: WORKDIR
      value: "/proc/self/fd/1"
```

2024-02-12 13:30 UTC, popeyeinit commented
> And if I interpret the [docker docs](https://docs.docker.com/engine/reference/builder/#workdir) correctly, the WORKDIR maybe specified also via environment variables, so the policy should also match on that in k8s manifests?

This is not correct. Although the environment variable `WORKDIR` may be set in an k8s manifest, it is not evaluated (picked up).

2024-03-03 00:06 UTC, chipzoller commented
This isn't going to work with the YAML anchors because Kyverno will interpret `spec.definitions.customCheck` as a literal path to the resource. Please re-write without using YAML anchors (but still using Kyverno validate anchors).

2024-03-06 14:18 UTC, chipzoller commented
@lobuhi, status?

2024-03-09 14:49 UTC, chipzoller commented
No response, closing.

2024-03-09 14:49 UTC, closed without merging