Add a sample policy to add node labels to pod
kyverno/policies pull request #914
Opened 2024-02-26 20:31 UTC by Chandan-DK

## Related Issue(s)
Closes #887 

## Description
Adds a new sample policy to add node labels to pod

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-03-01 12:21 UTC, chipzoller requested changes
I don't see here where you're removing the Binding resource filter from the ConfigMap.

2024-03-06 19:14 UTC, Chandan-DK commented on other/add-node-labels-pod/.chainsaw-test/chainsaw-test.yaml
> +          kubectl get configmap -n kyverno kyverno -o yaml | sed 's/\[Binding,\*,\*\]//g' - | sed 's/\[Pod\/binding,\*,\*\]//g' - | sed 's/\[Node\/\*,\*,\*\]//g' - | sed 's/\[Node,\*,\*\]//g' - | kub
@chipzoller The Binding resource filter from the ConfigMap is removed here

2024-03-09 14:25 UTC, chipzoller approved these changes

2024-03-09 14:25 UTC, merged

2025-03-07 18:02 UTC, isaac88 commented
Hello @Chandan-DK 

I just tested you Clusterpolicy example and I have the following error message

`
Operation cannot be fulfilled on pods "XXXXXXXXX │
│ ": the object has been modified; please apply your changes to the latest version and try again
`

Do you know why that's happening?