Added test for copy-ns-labels policy
kyverno/policies pull request #967
Opened 2024-04-11 18:28 UTC by siddhikhapare

## Related Issue(s)

Fixes #950 

## Description
added chainsaw test for [copy-namespace-labels](https://github.com/kyverno/policies/tree/main/other/copy-namespace-labels) policy to test working of policy for outside and within ns with owner and multiple additional labels.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-04-12 17:29 UTC, siddhikhapare commented
@chipzoller Could you help me in resolving this issue of test failures?

2024-04-12 17:41 UTC, chipzoller commented
Sure. Forget the failures for right now. I see you are missing some fundamental points of what this policy does.
**Hint:** Look at what the policy matches on versus what you're testing. Do they all make sense?

2024-04-12 18:34 UTC, siddhikhapare commented
> Sure. Forget the failures for right now. I see you are missing some fundamental points of what this policy does. **Hint:** Look at what the policy matches on versus what you're testing. Do they all make sense?

Thank you for your helpful response. As per my understanding ,in order to validate both conditions of policy simultaneously. I have to define both rules in single resource. Could you please share your thoughts on this?

2024-04-12 18:42 UTC, chipzoller commented
Not sure what you're saying. Look at my hint, then look at the policy match block, then look at all the resources you're trying to create as part of the test. Something is off there. What is it?

2024-04-12 19:04 UTC, siddhikhapare commented
> Not sure what you're saying. Look at my hint, then look at the policy match block, then look at all the resources you're trying to create as part of the test. Something is off there. What is it?

pod resource kind is not included in the match block which I have provided and rules will only apply to deployment resources which will create and manage the associated pods.

2024-04-12 19:12 UTC, siddhikhapare commented
@chipzoller I will update it.

2024-04-12 20:20 UTC, chipzoller commented
Yes, correct. Fix that first then let's look.

2024-04-13 16:54 UTC, siddhikhapare commented
Should use a ClusterRole to grant permissions here for this policy?

2024-04-13 18:16 UTC, chipzoller commented
There should be no need to grant permissions here.

2024-04-18 17:37 UTC, siddhikhapare commented
@chipzoller I've noticed that policy is taking more time to initialize. I tried increasing the sleep duration in `chainsaw-test.yaml` file but still providing me same error regarding policy status is ``null`` which I mentioned [here](https://live.staticflickr.com/65535/53661716587_0cb0e6caf3_b.jpg). Could you please help me in understanding what's causing this issue?

2024-04-18 19:14 UTC, siddhikhapare commented
I assert that `owner` label is not a static value, so we do not have to specify in ``values.yaml``.
`owner` label value is fetched dynamically from the namespace's metadata labels using the `apiCall` and `jmesPath` in the policy's context.

2024-04-20 14:53 UTC, chipzoller requested changes
Please look at the failed test log fro your error. You can and should also run this locally on your machine and you will see the same thing. You should always be running tests locally before pushing changes in a PR.

2024-04-21 18:23 UTC, siddhikhapare commented
> Please look at the failed test log fro your error. You can and should also run this locally on your machine and you will see the same thing. You should always be running tests locally before pushing changes in a PR.

I have tested my files using kyverno test previously. I have attached passed test output [here](https://live.staticflickr.com/65535/53669490335_3ce8f0df99_b.jpg) using chainsaw.

2024-04-21 18:43 UTC, siddhikhapare commented
@chipzoller  I tested files locally which have got output as passed tests as expected but here test are failed.

2024-04-21 18:59 UTC, chipzoller commented
Look at the logged output in CI tests here and see why they fail.

2024-04-22 17:07 UTC, siddhikhapare commented
for bad-deployment-with-ouside-ns resource have the `kubernetes.io/metadata.name` label. According to the policy, this label will not be copied to the deploy. However, other labels from the  ns should  be copied to the deployments. Therefore, this resource should fail because I didn't copy the owner label from the ns to the deploy before. It [failed](https://live.staticflickr.com/65535/53670676697_b41d03ee20_b.jpg) locally once because the API call is taking time to run, but it [passed](https://live.staticflickr.com/65535/53671910469_8ba9a4eb8e_b.jpg) the test once so I removed that resource.

2024-04-23 15:03 UTC, siddhikhapare commented
I think the tests were failing because of the `creationTimestamp` field, so I removed it . But when I ran the tests on locally, I found that they all passed, whether I included that field or not. You can see the results here [output](https://live.staticflickr.com/65535/53672653922_b565ed9c60_b.jpg
)

2024-04-23 15:38 UTC, chipzoller commented
You still don't seem to understand what this policy is about and how to test it. This is a mutation policy with two rules. There is no "bad" resource and no failure should occur. The test is about asserting on what the resulting mutation should look like, for both rules, in different scenarios with applicable resources.

2024-04-23 16:53 UTC, siddhikhapare commented
> You still don't seem to understand what this policy is about and how to test it. This is a mutation policy with two rules. There is no "bad" resource and no failure should occur. The test is about asserting on what the resulting mutation should look like, for both rules, in different scenarios with applicable resources.

I found [internal error](https://live.staticflickr.com/65535/53672885032_216c1374a8_b.jpg
) today that failed when calling the webhook "mutate-policy.kyverno.svc". However, according to this note mentioned in Kyverno's documentation https://kyverno.io/docs/writing-policies/mutate/ , Kubernetes disallows changes to certain fields in resources including `name, namespace, uid, kind, and apiVersion`, therefore you cannot use Kyverno policy to effect any of these fields either during admission or once a resource has been persisted. I thought I needed to change the `creationTimestamp` field, which indicates when an object was created. and this also mentioned in k8s doc here https://kubernetes.io/docs/concepts/workloads/pods/#pod-update-and-replacement so - Most of the metadata about a Pod is immutable that cannot change the `namespace, name, uid, or creationTimestamp fields`; the generation field is unique. It only accepts updates that increment the field's current value. This means that these fields can't be modified once they're set. 

I did not understand that error correctly so thanks for providing clarification.

2024-04-23 17:05 UTC, chipzoller commented
None of what you're saying matters in this case. A mutation during admission is not subject to these limitations since there is no "existing" resource. New resources being created are mutated before being persisted. All that's needed is to check the resource after it is created.

2024-04-26 18:29 UTC, siddhikhapare commented
All [test](https://live.staticflickr.com/65535/53679719537_7e14df85d5_b.jpg) passed as you have explained @chipzoller. Thanks for your guidance.

2024-04-27 05:59 UTC, siddhikhapare commented
I think this test might be showing there's a issue with resources timeout. Could you please provide your insights regarding this issue it would be helpful for me.

2024-04-30 14:09 UTC, chipzoller requested changes
Please also use an error step to fail if the `kubernetes.io/metadata.name` is found on at least one Deployment.

2024-04-30 14:09 UTC, chipzoller commented on other/copy-namespace-labels/.chainsaw-test/resource.yaml
> +    kubernetes.io/metadata.name: "my-deployment-2"
This shouldn't be here. Please remove. The label `kubernetes.io/metadata.name` is only found at the Namespace level.

2024-05-08 19:21 UTC, siddhikhapare commented
@chipzoller Sorry for delay in resolving issue. I was out of station. I have checked test here that `kubernetes.io/metadata.name` label for only one [resource](https://live.staticflickr.com/65535/53708386060_3c10efa1a9_b.jpg). I have checked for all resource definition also to matched that label and they should provide error - ```- error:
        resource:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            labels:
            
  namespace: within-ns
              
[kubernetes.io/metadata.name](http://kubernetes.io/metadata.name): within-ns``` for this I found this [output](https://live.staticflickr.com/65535/53708398535_c27409a1b4_b.jpg)

2024-05-08 19:30 UTC, chipzoller commented
So are you saying the previous comment is resolved? Ready for review again?

Also, in the future, there's no need to take a screenshot of terminal output. Please just paste the text into a code block here so it's easy to follow the path of communication.

2024-05-08 19:32 UTC, siddhikhapare commented
> kubernetes.io/metadata.name

yes I believe that all test passed for that change what you have suggested to add.

2024-05-08 19:35 UTC, siddhikhapare commented
I have added whole resource definition in test file if that kubernetes.io/metadata.name label found with value of the label is the namespace name then that resource should provide error.

2024-05-15 17:04 UTC, JimBugwadia commented
@siddhikhapare - has this requested change been addressed? 

https://github.com/kyverno/policies/pull/967#pullrequestreview-2031487506

2024-05-19 16:53 UTC, siddhikhapare commented
@JimBugwadia @chipzoller I have added [here](https://github.com/kyverno/policies/pull/967/commits/8e0c5492c380cb6729de295847a18a7537e7f113#diff-777abbfd7c3c06fd5fe0ec73c3a4b0284a58ea755e5b09046ecc9b1b44b33910R21) as whole deployment resource to check that label present or not because for all resources contain immutable label kubernetes.io/metadata.name which set by Kubernetes control plane on all namespaces so that resource error should found. I have tested that file locally, it passed test.

2024-05-21 18:43 UTC, chipzoller requested changes

2024-05-21 18:43 UTC, chipzoller commented on other/copy-namespace-labels/.chainsaw-test/patchresource.yaml
> +#Deployment with `kubernetes.io/metadata.name` label
Comment is no longer applicable.

2024-05-21 18:43 UTC, chipzoller commented on other/copy-namespace-labels/.chainsaw-test/patchresource.yaml
> +    env: dev
You're missing the `app` label from the source Deployment. You must assert that it is present as well.

2024-05-21 18:43 UTC, chipzoller commented on other/copy-namespace-labels/.chainsaw-test/resource.yaml
> +    owner: "any-corp"
You should change the value of this label and ensure it is overwritten with the label's value from the Namespace. The patched resource for this is fine, but change the value of `owner` here to something different.

2024-05-21 18:44 UTC, chipzoller requested changes

2024-05-21 18:44 UTC, chipzoller commented on other/copy-namespace-labels/.chainsaw-test/chainsaw-test.yaml
> +              app: my-app02
You don't need to error on `app`, only on `kubernetes.io/metadata.name`.

2024-05-26 18:09 UTC, siddhikhapare commented
@chipzoller Should I update the digest hash string in the `artifacthub-pkg.yml` file? I believe it should be updated when the policy definition changes. I'm not sure what the exact lint error is. Could you help me understand it better?

2024-05-26 18:11 UTC, siddhikhapare commented
I found this error  diff --git a/kasten/kasten-generate-policy-by-preset-label/artifacthub-pkg.yml b/kasten/kasten-generate-policy-by-preset-label/artifacthub-pkg.yml

2024-05-28 22:50 UTC, chipzoller commented
Sent #1036 to fix.

2024-05-28 23:23 UTC, chipzoller approved these changes
Nice work, thanks.

2024-05-28 23:24 UTC, merged