Replace k10-generate-gold-backup-policy ClusterPolicy
kyverno/policies pull request #998
Opened 2024-05-08 21:29 UTC by mattbator

## Related Issue(s)

N/A

## Description

Replaces `k10-generate-gold-backup-policy` with a version that checks for duplicate policies and can more easily be adapted to environmental needs. Filenames, policy/rule names, category, and keywords have been updated to reflect Kasten K10 rebranding to Veeam Kasten.

## Checklist

- [x] I have read the [policy contribution guidelines](https://github.com/kyverno/policies/blob/main/README.md#contribution).
- [x] I have added test manifests and resources covering both positive and negative tests that prove this policy works as intended.
- [x] I have added the artifacthub-pkg.yml file and have verified it is complete and correct.

2024-05-28 23:38 UTC, chipzoller commented on kasten/kasten-generate-example-backup-policy/artifacthub-pkg.yml
> +  kubectl apply -f https://raw.githubusercontent.com/kyverno/policies/main/kasten/kasten-generate-example-backup-policy/create-kasten-policies-clusterrole.yaml
```suggestion
```

2024-05-28 23:39 UTC, chipzoller commented on kasten/kasten-generate-example-backup-policy/artifacthub-pkg.yml
> +  Refer to the documentation for more details on Kyverno annotations: https://artifacthub.io/docs/topics/annotations/kyverno/
```suggestion
```

2024-05-31 13:52 UTC, chipzoller requested changes
One minor thing. I noticed when you had done this to previous samples, it broke our ability to render them to Markdown :)

2024-05-31 13:52 UTC, chipzoller commented on kasten/kasten-generate-example-backup-policy/kasten-generate-example-backup-policy.yaml
> +      Use with "kasten-data-protection-by-label" policy to require "dataprotection" labeling on workloads.
When using a folded line (block) scalar like this, you can't have an empty line or else it breaks rendering.
```suggestion
      Generates a Kasten policy for a namespace that includes any Deployment or StatefulSet with a "dataprotection=kasten-example" label, if the policy does not already exist. Use with "kasten-data-protection-by-label" policy to require "dataprotection" labeling on workloads.
```

2024-06-11 13:46 UTC, chipzoller commented
Ping @mattbator

2024-07-09 19:03 UTC, mattbator commented
Thanks for the support on changes required to play nicely with the ArtifactHub - should be in good shape now.

2024-07-10 17:36 UTC, mattbator commented
Good question! The original contribution was an early policy created by my predecessor prior to any test requirements. I was able to fumble my way through chainsaw updates to the other policies with minor changes, but believe I may have been a bit out of my depth on this one. Happy to take another pass at it if they're now required.

2024-07-10 17:39 UTC, chipzoller commented
Thanks for the info. I think this is fine.

2024-07-10 17:39 UTC, chipzoller approved these changes

2024-07-10 17:39 UTC, merged

2024-07-10 17:53 UTC, mattbator commented
Thank you!